### ISSUE TITLE
Parsing of nested JSON

### ISSUE THREAD

**Issue by 9point6** [kantord/emuto#567]
I have a use case where a large JSON object will contain nested JSON strings and can't seem to find a way to parse these nested JSON strings in emuto currently. It would be nice to be able to pipe into `JSON.parse`

**Comment by kantord** [comment]
That sound like a great idea. And it's really easy to implement, too, so I'll try to do it today :-)

**Comment by kantord** [comment]
There you go, here's an MR: https://github.com/kantord/emuto/pull/568

is it roughly what you meant?

**Comment by kantord** [comment]
Should be released in a few minutes!

**Comment by 9point6** [comment]
That's amazing! Thanks for the quick turnaround!
