### ISSUE TITLE
Allow infix function calls

### ISSUE THREAD

**Issue by kantord** [kantord/emuto#78]
Example:

```
({"foo": "bar"} has "foo") // returns true
({"foo": "bar"} has "bar") // returns false
```

`({"foo": "bar"} has "foo")` should be equivalent to `{"foo": "bar"} | has "foo"`

**Comment by jacekk** [comment]
@kantord Can you check if #82 is sufficient?

**Comment by kantord** [comment]
@jacekk sure! Thanks for your contribution. I added a bunch of comments at your PR.

Just one note: please next time don't take an issue that is already assigned to someone else. I will add a bunch of new issues so if you're looking for challenges, you'll have a bunch of tasks to take! :-) I'll also add guidelines and documentation to make things easier for contributors! Mea culpa

**Comment by jacekk** [comment]
@kantord This seemed like the easiest issue I can handle. I was aware it had been assigned, and I wholeheartedly apologize.
