### ISSUE TITLE
Add git hook

### ISSUE THREAD

**Issue by kantord** [kantord/emuto#93]
`yarn test` and `yarn checks` should be always executed before commit, as well as commit message format enforcement

**Comment by jacekk** [comment]
I guess this could be the easiest way: https://github.com/typicode/husky , but I've used https://github.com/okonet/lint-staged several times and it works great. I dunno if **husky** supports executing hooks on staged changes only.

**Comment by kantord** [comment]
Yes! I think husky will be perfect for us.

I've seen it in use in this project: https://github.com/kantord/smart-faq/blob/master/package.json#L32

Worked perfectly there. We need commitlint here as well + we also need to execute tests and checks in the same hook an we're done.

If you want to take this issue, you are welcome to do it! :-)

**Comment by jacekk** [comment]
Seems easier than the `in` issue ;) Will work on it in the evening.
